import { verifyToken } from 'lib/vip/token';
import { resolveDriver } from 'lib/vip/drivers';
import { ReviewScreen, ProblemScreen } from '../../_review/review-screen';

// Every scan carries a different token, so this page is always rendered fresh.
export const dynamic = 'force-dynamic';

export const metadata = { title: 'Thank you' };

/**
 * The signed-QR entry point. Carries booking reference, vehicle and an expiry,
 * and cannot be forged. Generated by the QR studio.
 */
export default async function TokenReviewPage({ params }) {
    const { token } = await params;
    const result = verifyToken(token);

    if (!result.ok) {
        const expired = result.reason === 'expired';
        return (
            <ProblemScreen
                titleKey={expired ? 'expiredTitle' : 'invalidTitle'}
                bodyKey={expired ? 'expiredBody' : 'invalidBody'}
            />
        );
    }

    const driver = await resolveDriver(result.claim);
    return <ReviewScreen driver={driver} bookingRef={result.claim.bookingRef} vehicle={result.claim.vehicle} />;
}
